name: Run tests

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test && Benchmarks
        run: go test -v -bench=. ./...
